//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desafio_WF_V3.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class EMPLEADO
    {
        public string Dni { get; set; }
        public string Nombre { get; set; }
        public string Apellidos { get; set; }
        public string Email { get; set; }
        public string Domicilio { get; set; }
        public byte[] Foto { get; set; }
        public string Empresa { get; set; }
    
        public virtual EMPRESA EMPRESA1 { get; set; }
    }
}
