//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Desafio_WF_V3.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bd_ertesEntities : DbContext
    {
        public bd_ertesEntities()
            : base("name=bd_ertesEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<EMPLEADO> EMPLEADOS { get; set; }
        public virtual DbSet<EMPRESA> EMPRESAS { get; set; }
        public virtual DbSet<ERTE> ERTES { get; set; }
        public virtual DbSet<SECTORE> SECTORES { get; set; }
    }
}
